### ISSUE TITLE
support play_url and launch_app

### ISSUE THREAD

**Issue by twocolors** [sebbo2002/node-pyatv#104]
hi, can you tell me when there will be support?
or how to send these commands?

**Comment by sebbo2002** [comment]
Both commands are currently not implemented, because they do not exist in `atvscript` as far as I know. If it does, I would be very happy to see the relevant documentation. Currently this library only implements these commands.

**Comment by twocolors** [comment]
yes atvscript not support this command, but atvremote work this command
https://pyatv.dev/development/apps/

**Comment by sebbo2002** [comment]
This library currently only implements what atvscript can do. But feel free to implement more and open a PR, I would be happy to see that.

**Comment by twocolors** [comment]
you write beautifully and with tests, not all PR will look good here. didn't think to just add execAtvremote and catch only error?

**Comment by twocolors** [comment]
@sebbo2002 hi, i see you add turnOn and turnOff. 
plz add launch_app and play_url

**Comment by postlund** [comment]
They are easy to implement. Feel free to open a feature request for them and I can try to fix that.
