### ISSUE TITLE
Error Installing node-pyatv

### ISSUE THREAD

**Issue by jmhitchcock314** [sebbo2002/node-pyatv#235]
When I attempt to install node-pyatv on my Windows 10 machine I get the error below.  Do you have any suggestions on a workaround?

> 84 verbose stack Error: command failed
> 84 verbose stack     at ChildProcess.<anonymous> 
> C:\Users\Woodstock\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
> 84 verbose stack     at ChildProcess.emit (node:events:513:28)
> 84 verbose stack     at maybeClose (node:internal/child_process:1091:16)
> 84 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
> 85 verbose pkgid @sebbo2002/node-pyatv@6.0.3
> 86 verbose cwd C:\Windows\System32
> 87 verbose Windows_NT 10.0.19045
> 88 verbose node v18.16.0
> 89 verbose npm  v9.6.7
> 90 error code 1
> 91 error path C:\Windows\System32\node_modules\@sebbo2002\node-pyatv
> 92 error command failed
> 93 error command C:\Windows\system32\cmd.exe /d /s /c ./check.sh
> 94 error '.' is not recognized as an internal or external command,
> 94 error operable program or batch file.
> 95 verbose exit 1

**Comment by sebbo2002** [comment]
I have not tested `node-pyatv` on Windows and I do not have a PC with Windows available myself to use for testing. I guess that Windows cannot run shell scripts natively? When the module is installed, the [`check.sh`](https://github.com/sebbo2002/node-pyatv/blob/develop/check.sh) is executed, which prints an [appropriate message](https://github.com/sebbo2002/node-pyatv/blob/develop/src/bin/check.ts) to the console if pyatv should not be installed.
