### ISSUE TITLE
`output_devices` in response of `atvscript push_updates` resulting in faulty state

### ISSUE THREAD

**Issue by maxileith** [sebbo2002/node-pyatv#295]
Hi @sebbo2002 ,

this Issue is related to #291. An user of my plugin @rvetere has reported the issue https://github.com/maxileith/homebridge-appletv-enhanced/issues/155. After some investigation the root cause is similar to the on reported in #291. Below is the response of `atvscript push_updates`…

```json
{"result": "success", "datetime": "2024-01-11T19:45:57.122827+01:00", "power_state": "on"}
{"result": "success", "datetime": "2024-01-11T19:45:57.123138+01:00", "output_devices": [{"name": "Apple TV", "identifier": "D4ED48E4-4C88-47C0-B05C-077747F85C5D"}]}
{"result": "success", "datetime": "2024-01-11T19:45:57.125393+01:00", "hash": "ca496c14642c78af6dd4250191fe175f6dafd72b4c33bcbab43c454aae051da1", "media_type": "unknown", "device_state": "idle", "title": null, "artist": null, "album": null, "genre": null, "total_time": null, "position": null, "shuffle": "off", "repeat": "off", "series_name": null, "season_number": null, "episode_number": null, "content_identifier": null, "app": null, "app_id": null}
{"result": "success", "datetime": "2024-01-11T19:45:57.126692+01:00", "volume": 50.0}
```

… which does include a line with the unexpected attribute `output_devices` which I do not think is correctly handled here: https://github.com/sebbo2002/node-pyatv/blob/60a414daeaac29c53254611ef25a54dbf671a720/src/lib/device-events.ts#L38-L52 I think it should be handled like `power_state` or `volume`

**Comment by sebbo2002** [comment]
The field `output_devices` is currently not implemented and is therefore neither mapped in events nor in `NodePyATVState`. I'll put it on my todo list, I'm assuming to have something by the beginning to mid of next week...

**Comment by maxileith** [comment]
The problem is, that this function will return its default when passing an Object just with `output_devices`, so `null` for every attribute.

https://github.com/sebbo2002/node-pyatv/blob/60a414daeaac29c53254611ef25a54dbf671a720/src/lib/tools.ts#L237

Then the following method will set all states to `null`.

https://github.com/sebbo2002/node-pyatv/blob/60a414daeaac29c53254611ef25a54dbf671a720/src/lib/device-events.ts#L38

So I would consider this a bug, not an enhancement.

**Comment by sebbo2002** [comment]
Oh. I'm glad you wrote again. I somehow didn't realize that the first time I read it. Yes, of course I should fix that also, so that `applyStateAndEmitEvents` does not trigger any events if everything is set to `null`. That would solve the problem, right?

**Comment by sebbo2002** [comment]
@maxileith Both should be fixed with `7.3.0-develop.1`. Can you confirm that the fix works?

**Comment by maxileith** [comment]
I think there is a change required, see #299. Nevertheless, I want to thank you for the fast replies and fixes in this project.

**Comment by sebbo2002** [comment]
#300 merged in favor of #299.

**Comment by maxileith** [comment]
@sebbo2002 I left a comment in #300. You may want to take a look at this. However, this feature should work either way for me. I will release a beta of my plugin and ask the author of the bug reported if it is working for him 👍🏻

**Comment by maxileith** [comment]
One minor thing ... `get outputDevices()` seems to be missing on `NodePyATVDevice`.

**Comment by maxileith** [comment]
One minor thing ... `get outputDevices()` seems to be missing on `NodePyATVDevice`.
