### ISSUE TITLE
Is it possible to support double tap key press?

### ISSUE THREAD

**Issue by zhiningq** [sebbo2002/node-pyatv#325]
My goal is to be able to force quit an app using double tap home key and swipe up:

It can only be achieved using workaround
* atvremote -s <host> home home // calling this can show a list of background apps
* atvremote -s <host > up up // calling this can exit the current app

Is it possible to allow keyPress to take an array instead of just a single key? https://github.com/sebbo2002/node-pyatv/blob/7e6eefa8df87d73c4129bdc6d24148fe8ea9976d/src/lib/device.ts#L350

or if we could support double tap on keyPress with InputAction https://github.com/postlund/pyatv/blob/master/pyatv/interface.py#L372

**Comment by sebbo2002** [comment]
Sounds absolutely feasible, implementing `InputAction` would probably make more sense. Unfortunately I have a lot to do at the moment, but if it's not urgent I would take care of it in the next few weeks. Otherwise, I'm also happy to accept pull requests if it's urgent.

**Comment by sebbo2002** [comment]
I had a quick look at the whole thing. Currently `InputAction` does not seem to be available for `atvscript` (which is used by this library for most key actions), also `home home` or `up up` does not work here:

```
❯❯❯ atvscript -s up up
usage: atvscript [-h] [--storage {file,none}] [--storage-filename STORAGE_FILENAME] [-i ID] [--protocol PROTOCOL] [-s SCAN_HOSTS] [--output OUTPUT] [--debug]
                 [--dmap-credentials DMAP_CREDENTIALS] [--mrp-credentials MRP_CREDENTIALS] [--airplay-credentials AIRPLAY_CREDENTIALS]
                 [--companion-credentials COMPANION_CREDENTIALS] [--raop-credentials RAOP_CREDENTIALS]
                 command
atvscript: error: unrecognized arguments: up
```

Do you happen to know how to double-click in `atvscript`? Otherwise this feature would have to be implemented in `pyatv`'s `atvscript` first. The best thing to do is to open a ticket there and explain your requirements.

**Comment by maxileith** [comment]
That is how I implemented it in homebridge-appletv-enhanced. "Avadra Kedavra" closes opened apps. This is of course not very configurable and specific to my plugin but you should get an idea how it works.

https://github.com/maxileith/homebridge-appletv-enhanced/blob/e76051886273fef47abd6f24559ca6e9dfe82f58/src/RocketRemote.ts#L191-L204
