### ISSUE TITLE
Adding missing attributes from atvscript

### ISSUE THREAD

**Issue by maxileith** [sebbo2002/node-pyatv#339]
Hi @sebbo2002,

I just wanted to ask if you could add the attributes `season_number`, `series_name` and `episode_number` to this library. I actually have never seen them have a value besides `null`, but I assume `season_number` and `episode_number` would be integers and `series_name` a string.

I know this sound weird because I have never seen any actual values but I would love to see this library be complete.

`atvscript` output:

```json
{
    "result": "success",
    "datetime": "2024-10-01T20:32:46.708220+02:00",
    "hash": "j41OXof0i::cxIVjM4rB",
    "media_type": "music",
    "device_state": "paused",
    "title": "In the Air Tonight",
    "artist": "Phil Collins",
    "album": "Face Value (Deluxe Edition)",
    "genre": "Rock",
    "total_time": 335,
    "position": 100,
    "shuffle": "songs",
    "repeat": "all",
    "series_name": null,
    "season_number": null,
    "episode_number": null,
    "content_identifier": null,
    "app": "Musik",
    "app_id": "com.apple.TVMusic"
}

```

**Comment by sebbo2002** [comment]
A brief update from me: I'm currently on vacation and would like to tackle the topic after my vacation as soon as I find some time. It seems to have some time. So don't be surprised if not much happens here for the next few weeks.

**Comment by maxileith** [comment]
Yeah no problem. Take your time and have nice vacation :)
