### ISSUE TITLE
Airplay2 (Stereo) Speaker support ?

### ISSUE THREAD

**Issue by cgHome** [sebbo2002/node-pyatv#93]
Guten Tag,

While searching for a way to integrate AppleTV and Airplay 2 for the Homey Smart Home, I came across your node implementation via the pyatv python library.

My basic question is, do you support normal Airplay2 (stereo) speaker devices like HomePod mini besides AppleTV ?

Gruss Chris

**Comment by sebbo2002** [comment]
In general, node-pyatv is only a client for [pyatv](https://pyatv.dev/). If these speakers are supported by pyatv, they should also work with node-pyatv. If in doubt, just try it out. 

You might also be interested in the [pyatv-mqtt-bridge](https://github.com/sebbo2002/pyatv-mqtt-bridge) project, which would allow you to use node-pyatv directly via MQTT.
